---
homebrew_installed_packages:
  - applesimutils
  - idb-companion
  - node
  - ruby
  - watchman
  - zsh

homebrew_taps:
  - facebook/fb
  - homebrew/cask
  - homebrew/core
  - wix/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - altair-graphql-client
  - android-studio
  - flipper
  - react-native-debugger

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages:
  - cocoapods

npm_packages:
  - detox-cli

pip_packages:
  - name: fb-idb
    executable: pip3

# Install avd devices
# Note: Add zip path with the avd folder and ini file to install in .android/avd
# make sure that the ini file matches the name
# e.g. name: Pixel_3a_XL_API_28 ini_file: Pixel_3a_XL_API_28.ini
avd_archives:
  []
  # - {
  #     name: Pixel_3a_XL_API_28,
  #     src: "https://drive.google.com/u/0/uc?export=download&confirm=m4Uy&id=1VrsFOVY9V1m2ei9gDHrEqJer4CRZnszK",
  #   }
