---
homebrew_installed_packages:
  - applesimutils
  - idb-companion
  - node
  - ruby
  - watchman
  - zsh

homebrew_taps:
  - facebook/fb
  - homebrew/cask
  - homebrew/core
  - wix/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - altair-graphql-client
  - android-studio
  - flipper
  - react-native-debugger

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode (11.7)" }
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages:
  - cocoapods

npm_packages:
  - detox-cli

pip_packages:
  - name: fb-idb
    executable: pip3

# Install avd devices archive stored in google drive
# Note: Add google drive share id to avd archive to install in .android/avd
# make sure that the ini file matches the name
# e.g. name: Pixel_3a_XL_API_28 ini_file: Pixel_3a_XL_API_28.ini
avd_archives:
  - { name: Pixel_3a_XL_API_28, id: "1VrsFOVY9V1m2ei9gDHrEqJer4CRZnszK" }
