---
homebrew_installed_packages:
  - applesimutils
  - node
  - ruby
  - watchman

homebrew_taps:
  - homebrew/cask
  - homebrew/core
  - wix/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - altair-graphql-client
  - android-studio
  - flipper
  - react-native-debugger

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  - cocoapods
npm_packages:
  - name: detox-cli
    global: yes
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
