---
homebrew_installed_packages:
  - applesimutils
  - idb-companion
  - node
  - ruby
  - watchman
  - zsh

homebrew_taps:
  - facebook/fb
  - homebrew/cask
  - homebrew/core
  - wix/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - altair-graphql-client
  - android-studio
  - flipper
  - react-native-debugger

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A

gem_packages:
  - cocoapods

npm_packages:
  - detox-cli

pip_packages:
  - name: fb-idb
    executable: pip3

# Install avd devices
# Note: Add zip with the avd folder and ini file
# to the avd-arc folder that matches the zip name
# (e.g. arc: Pixel_3a_XL_API_28.zip, item: Pixel_3a_XL_API_28)
avd_archives:
  - Pixel_3a_XL_API_28
