---
homebrew_taps:
  - aws/tap
  - homebrew/cask
  - homebrew/core

homebrew_installed_packages:
  - aws-sam-cli
  - ctop
  - fish
  - httpie
  - jq
  - nvm
  - terraform
  - tree

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-studio
  - cheatsheet
  - discord
  - docker
  - firefox-developer-edition
  - gitkraken
  - iterm2
  - postman
  - slack
  - spotify
  - vagrant
  - vagrant-manager
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - {id: 1116599239, name: "NordVPN IKE - Unlimited VPN"}
  - {id: 1461456897, name: "Tyme 3 - Time tracking"}
  - {id: 405843582, name: "Alfred"}
  - {id: 441258766, name: "Magnet"}
  - {id: 668208984, name: "GIPHY Capture. The GIF Maker"}
  - {id: 926036361, name: "LastPass Password Manager"}
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages:
  #- cocoapods

npm_packages:
  #- detox-cli

pip_packages:
  - name: awscli
    executable: pip3
