---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps|bool
      tags: ['mas']

  tasks:
    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
