---
- hosts: all
  connection: local

  vars:
      the_user: "{{ ansible_user_id }}"

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps|bool
      tags: ['mas']

  tasks:
    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - include_tasks: tasks/avd-devices.yml
      tags: ['avd-devices']

    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh
