---
- hosts: all
  connection: local

  vars:
      the_user: "{{ ansible_user_id }}"

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps|bool
      tags: ['mas']

  tasks:
    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - include_tasks: tasks/avd-devices.yml
      tags: ['avd-devices']

    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: Add Android configs to zshrc
      blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        block: |
          # Android
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$PATH:$ANDROID_HOME/emulator
          export PATH=$PATH:$ANDROID_HOME/tools
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          export PATH=$PATH:$ANDROID_HOME/platform-tools

          # JAVA
          export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"
          export PATH=$PATH:$JAVA_HOME/bin
