---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
