---
- hosts: 127.0.0.1
  connection: local

  vars:
    the_user: "{{ ansible_user_id }}"
    git_name: "KirioXX"
    git_email: "wunderlich.ben@gmail.com"

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mas
      when: mas_installed_apps|bool
      tags: ["mas"]

  tasks:
    - include_tasks: tasks/extra-packages.yml
      tags: ["git"]

    - include_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - name: change user shell to fish
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/fish
