- name: configure git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"

- name: configure git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: configure git editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim

- name: set pull to rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true

- name: add alias for pretty logs `git lg`
  community.general.git_config:
    name: alias.lg
    scope: global
    value: log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit

- name: add config to use main branch on init
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
